import json

with open("json/cssci-plus-extend-partial.json", "r", encoding="utf-8") as f:
    data = json.load(f)

xmlUrlBase = "https://nxgp.cnki.net/knavi/rss/"
htmlUrlBase = "https://navi.cnki.net/knavi/JournalDetail?pcode=CJFD&amp;pykm="

subjectDict = {
    "综合性高校学报": "zonghe_gaoxiao",
    "高校社科学报": "gaoxiao_sheke",
    "综合性社会科学": "zonghe_shehui",
    "图书馆、情报与文献学": "tushu_qingbao",
    "政治学": "zhengzhi",
    "管理学": "guanli",
    "社会学": "shehui",
}

for subject in data:
    filename = subjectDict[subject] + ".opml"
    with open("opml/" + filename, "w", encoding="utf-8") as f:
        f.write(r'''<?xml version="1.0" encoding="UTF-8"?>''')
        f.write("\n")
        f.write(r'''<opml version="1.0">''')
        f.write("\n")
        f.write(" " * 2)
        f.write("<head>")
        f.write("\n")
        f.write(" " * 4)
        f.write("<title>" + filename + " generated by Zheng Shuai</title>")
        f.write("\n")
        f.write(" " * 2)
        f.write("</head>")
        f.write("\n")
        f.write(" " * 2)
        f.write("<body>")
        f.write("\n")
        f.write(" " * 4)
        f.write("<outline text=\"" + subject + "\" title=\"" + subject + "\">")

        for journal, pykm in data[subject].items():
            tail = pykm
            xmlUrl = xmlUrlBase + tail
            htmlUrl = htmlUrlBase + tail
            f.write("\n")
            f.write(" " * 6)
            f.write("<outline text=\"" + journal + "\" title=\"" + journal + "\" type=\"rss\" xmlUrl=\"" + xmlUrl + "\" htmlUrl=\"" + htmlUrl + "\"/>")

        f.write("\n")
        f.write(" " * 4)
        f.write("</outline>")
        f.write("\n")
        f.write(" " * 2)
        f.write("</body>")
        f.write("\n")
        f.write("</opml>")
