import json

with open("json/cssci-plus-extend-partial.json", "r", encoding="utf-8") as f:
    data = json.load(f)

xmlUrlBase = "https://nxgp.cnki.net/knavi/rss/"
htmlUrlBase = "https://navi.cnki.net/knavi/JournalDetail?pcode=CJFD&pykm="

for subject in data:
    with open("opml/" + subject + ".opml", "w", encoding="utf-8") as f:
        f.write(r'''<?xml version="1.0" encoding="UTF-8"?>''')
        f.write("\n")
        f.write(r'''<opml version="1.0">''')
        f.write("\n")
        f.write("  ")
        f.write("<head>")
        f.write("\n")
        f.write("    ")
        f.write("<title>" + subject + " generated by Zheng Shuai</title>")
        f.write("\n")
        f.write("  ")
        f.write("</head>")
        f.write("\n")
        f.write("  ")
        f.write("<body>")
        f.write("\n")
        f.write("    ")
        f.write("<outline text=\"" + subject + "\" title=\"" + subject + "\">")

        for journal,pykm in data[subject].items():
            tail = pykm
            xmlUrl = xmlUrlBase + tail
            htmlUrl = htmlUrlBase + tail
            f.write("\n")
            f.write("      ")
            f.write("<outline text=\"" + journal + "\" title=\"" + journal + "\" type=\"rss\" xmlUrl=\"" + xmlUrl + "\" htmlUrl=\"" + htmlUrl + "\"/>")

        f.write("\n")
        f.write("    ")
        f.write("</outline>")
        f.write("\n")
        f.write("  ")
        f.write("</body>")
        f.write("\n")
        f.write("</opml>")
        